.github/workflows/dotnet.yml, BB84.Extensions.sln, Directory.Build.props, dotnet-releaser.toml, src/BB84.Extensions/BB84.Extensions.csproj
changes:
- dotnet.yml modified
- project fixes
- build props fixed
- dotnet releaser toml added
closes #2
=> feat: add dotnet releaser

Directory.Build.props, src/BB84.Extensions/BooleanExtensions.cs, tests/BB84.ExtensionsTests/BooleanExtensionsTests.cs
changes:
- extensions methods added
closes #4
=> feat: boolean extensions

src/BB84.Extensions/EnumeratorExtensions.cs, src/BB84.Extensions/ListExtensions.cs, src/BB84.Extensions/Serialization/JsonExtensions.cs, src/BB84.Extensions/StringExtensions.cs, tests/BB84.ExtensionsTests/ByteExtensionsTests.cs, tests/BB84.ExtensionsTests/DateTimeExtensionTests.cs, tests/BB84.ExtensionsTests/EnumerableExtensionsTests.ForEach.cs, tests/BB84.ExtensionsTests/EnumerableExtensionsTests.cs, tests/BB84.ExtensionsTests/EnumeratorExtensionsTests.ToInt.cs, tests/BB84.ExtensionsTests/EnumeratorExtensionsTests.ToList.cs, tests/BB84.ExtensionsTests/EnumeratorExtensionsTests.cs, tests/BB84.ExtensionsTests/ListExtensionsTests.AddIfNotNull.cs, tests/BB84.ExtensionsTests/ListExtensionsTests.AddRangeIfNotNull.cs, tests/BB84.ExtensionsTests/ListExtensionsTests.cs, tests/BB84.ExtensionsTests/Serialization/JsonExtensionsTests.cs, tests/BB84.ExtensionsTests/Serialization/XmlExtensionTests.cs, tests/BB84.ExtensionsTests/StringExtensionsTests.Format.cs, tests/BB84.ExtensionsTests/StringExtensionsTests.FromBase64.cs, tests/BB84.ExtensionsTests/StringExtensionsTests.ToBase64.cs, tests/BB84.ExtensionsTests/StringExtensionsTests.cs
changes:
- unit tests fixed
closes https://github.com/BoBoBaSs84/BB84.Extensions/issues/6
=> feat: Add more unit tests

Directory.Build.props, README.md
changes:
- build props fixed
- readme fixed
closes #10
=> fix: license fix

.github/workflows/ci.yml, BB84.Extensions.sln, Directory.Build.props, README.md, dotnet-releaser.toml
changes:
- fixed the build props
- updated build workflow
- updated toml file
- updated readme file
closes #12
=> fix: build props

Directory.Build.props
changes:
- build props modified
closes #14
=> feat: enable package validation

.github/workflows/ci.yml, BB84.Extensions.sln, Directory.Build.props, src/BB84.Extensions/ObjectExtensions.cs, tests/BB84.ExtensionsTests/ObjectExtensionsTests.ToInt32Invariant.cs, tests/BB84.ExtensionsTests/ObjectExtensionsTests.cs
changes:
- framework issues fixed
- object extensions added
- integer extensions removed
closes #16; #17
=> fix: integer extensions vs. object extensions

Directory.Build.props, dotnet-releaser.toml
changes:
- `dotnet-releaser.toml` updated
- `Directory.Build.props` updated
=> fix: small nuget package fixes

Directory.Build.props, Directory.Build.targets, src/BB84.Extensions/ObjectExtensions.cs, src/BB84.Extensions/StringExtensions.cs, tests/BB84.ExtensionsTests/Helper/StringWriterWithEncodingTests.cs, tests/BB84.ExtensionsTests/ObjectExtensionsTests.ToBooleanInvariant.cs, tests/BB84.ExtensionsTests/ObjectExtensionsTests.ToDateTimeInvariant.cs, tests/BB84.ExtensionsTests/ObjectExtensionsTests.ToDecimalInvariant.cs, tests/BB84.ExtensionsTests/ObjectExtensionsTests.ToDoubleInvariant.cs, tests/BB84.ExtensionsTests/ObjectExtensionsTests.ToInt16Invariant.cs, tests/BB84.ExtensionsTests/ObjectExtensionsTests.ToInt32Invariant.cs, tests/BB84.ExtensionsTests/ObjectExtensionsTests.ToInt64Invariant.cs, tests/BB84.ExtensionsTests/ObjectExtensionsTests.ToStringInvariant.cs
changes:
- more object extensions added
- small fixes
- build targets file removed
- version bump
closes https://github.com/BoBoBaSs84/BB84.Extensions/issues/20
=> feat: add more object extensions

src/BB84.Extensions/EnumeratorExtensions.cs, tests/BB84.ExtensionsTests/EnumeratorExtensionsTests.Count.cs
changes:
- extension method added
- unit test added
closes #22
=> feat: enumerator extensions count

src/BB84.Extensions/IntegerExtensions.cs, tests/BB84.ExtensionsTests/IntegerExtensionsTests.ArrayDown.cs, tests/BB84.ExtensionsTests/IntegerExtensionsTests.ArrayUp.cs, tests/BB84.ExtensionsTests/IntegerExtensionsTests.For.cs, tests/BB84.ExtensionsTests/IntegerExtensionsTests.cs
changes:
- the `For` method added
- the `ArrayUp` method added
- the `ArrayDown` method added
closes #24
=> feat: integer extensions

BB84.Extensions.sln, Directory.Build.props, Directory.Build.targets, src/BB84.Extensions/EnumeratorExtensions.cs, src/BB84.Extensions/IntegerExtensions.cs, tests/BB84.ExtensionsTests/EnumeratorExtensionsTests.Count.cs, tests/BB84.ExtensionsTests/IntegerExtensionsTests.ArrayDown.cs, tests/BB84.ExtensionsTests/IntegerExtensionsTests.ArrayUp.cs, tests/BB84.ExtensionsTests/IntegerExtensionsTests.For.cs, tests/BB84.ExtensionsTests/IntegerExtensionsTests.cs
- new release
- minor version bump
closes #22 ; #24 ; #26
=> feat: dev -> main

src/BB84.Extensions/Serialization/JsonExtensions.cs, tests/BB84.ExtensionsTests/Serialization/JsonExtensionsTests.cs
changes:
- renamed method
- fixed unit test
closes #29
=> fix: json extensions

src/BB84.Extensions/StringExtensions.cs, tests/BB84.ExtensionsTests/StringExtensionsTests.Equals.cs
changes:
- `EqualsCaseSensitive` method added
- `EqualsIgnoreCase` method added
closes #28
=> feat: string extensions equals invariant

src/BB84.Extensions/ComparableExtensions.IsGreaterOrEqualThan.cs, src/BB84.Extensions/ComparableExtensions.IsGreaterThan.cs, src/BB84.Extensions/ComparableExtensions.IsLessOrEqualThan.cs, src/BB84.Extensions/ComparableExtensions.IsLessThan.cs, src/BB84.Extensions/ComparableExtensions.cs, tests/BB84.ExtensionsTests/ArrayExtensionsTests.RandomChoice.cs, tests/BB84.ExtensionsTests/ComparableExtensionsTests.IsGreaterOrEqualThan.cs, tests/BB84.ExtensionsTests/ComparableExtensionsTests.IsGreaterThan.cs, tests/BB84.ExtensionsTests/ComparableExtensionsTests.IsLessOrEqualThan.cs, tests/BB84.ExtensionsTests/ComparableExtensionsTests.IsLessThan.cs, tests/BB84.ExtensionsTests/ComparableExtensionsTests.cs
changes:
- the `IsGreaterOrEqualThan` method added
- the `IsGreaterThan` method added
- the `IsLessOrEqualThan` method added
- the `IsLessThan` method added
- unit tests namespace fixed
closes #42
=> feat: comparable extensions

Directory.Build.props, src/BB84.Extensions/ArrayExtensions.RandomChoice.cs, src/BB84.Extensions/BooleanExtensions.IsTrue.cs, src/BB84.Extensions/ByteExtensions.Compress.cs, src/BB84.Extensions/ByteExtensions.Decompress.cs, src/BB84.Extensions/DateTimeExtensions.EndOfMonth.cs, src/BB84.Extensions/DateTimeExtensions.EndOfWeek.cs, src/BB84.Extensions/DateTimeExtensions.StartOfMonth.cs, src/BB84.Extensions/DateTimeExtensions.StartOfWeek.cs, src/BB84.Extensions/EnumeratorExtensions.GetInt.cs, src/BB84.Extensions/EnumeratorExtensions.GetValues.cs, src/BB84.Extensions/StringExtensions.Compress.cs, src/BB84.Extensions/StringExtensions.Decompress.cs, tests/BB84.ExtensionsTests/ComparableExtensionsTests.IsGreaterOrEqualThan.cs, tests/BB84.ExtensionsTests/ComparableExtensionsTests.IsGreaterThan.cs, tests/BB84.ExtensionsTests/ComparableExtensionsTests.IsLessOrEqualThan.cs, tests/BB84.ExtensionsTests/ComparableExtensionsTests.IsLessThan.cs, tests/BB84.ExtensionsTests/EnumeratorExtensionsTests.GetInt.cs, tests/BB84.ExtensionsTests/EnumeratorExtensionsTests.GetValues.cs
changes:
- added `compress` method
- added `decompress` method
- did some refactoring
- comments added and documentation fixed
- version bump to 1.5.0
closes https://github.com/BoBoBaSs84/BB84.Extensions/issues/44
=> feat: byte extensions

src/BB84.Extensions/ByteExtensions.GetString.cs, src/BB84.Extensions/StringExtensions.Compress.cs, src/BB84.Extensions/StringExtensions.Decompress.cs, src/BB84.Extensions/StringExtensions.GetBytes.cs, tests/BB84.ExtensionsTests/ByteExtensionsTests.GetString.cs, tests/BB84.ExtensionsTests/ByteExtensionsTests.cs, tests/BB84.ExtensionsTests/StringExtensionsTests.GetBytes.cs, tests/BB84.ExtensionsTests/StringExtensionsTests.cs
- added the `GetBytes` method for `string` values
- added the `GetString` method for `byte` array values
- added a optional `Encoding` parameter
- some methods refactored
closes #46
=> feat: add string extensions and byte extensions

src/BB84.Extensions/IntegerExtensions.For.cs, tests/BB84.ExtensionsTests/IntegerExtensionsTests.For.cs
changes:
- method fixed
- unit test fixed
closes #48
=> fix: integer extension method for

src/BB84.Extensions/StringExtensions.FromBase64.cs, src/BB84.Extensions/StringExtensions.RemoveLinebreak.cs, src/BB84.Extensions/StringExtensions.RemoveWhitespace.cs, src/BB84.Extensions/StringExtensions.cs, tests/BB84.ExtensionsTests/StringExtensionsTests.RemoveLinebreaks.cs, tests/BB84.ExtensionsTests/StringExtensionsTests.RemoveWhitespace.cs
changes:
- added `RemoveWhitespace` method
- added `RemoveLinebreak` method
closes #51 & #52
=> feat: string extensions - remove whitespace method

Directory.Build.props
changes:
- updated `Directory.Build.props`
=> chore: version bump to 1.7.1

Directory.Build.props, README.md, src/BB84.Extensions/EnumerableExtensions.ForEach.cs
changes:
- version bump to `1.7.2`
- modified `README.md`
- fixed some comments
closes #38
=> chore(docs): improved documentation

.github/workflows/ci.yml, Directory.Build.props
changes:
- added support for `net8.0`
- version bump to `1.7.3`
closes #58
=> feat: support .net8.0

Directory.Build.props, src/BB84.Extensions/BooleanExtensions.IsNull.cs, src/BB84.Extensions/ByteExtensions.IsNull.cs, src/BB84.Extensions/FloatExtensions.IsNull.cs, src/BB84.Extensions/FloatExtensions.cs, src/BB84.Extensions/IntegerExtensions.IsNull.cs, src/BB84.Extensions/StringExtensions.IsNull.cs, tests/BB84.ExtensionsTests/BooleanExtensionsTests.IsFalse.cs, tests/BB84.ExtensionsTests/BooleanExtensionsTests.IsNull.cs, tests/BB84.ExtensionsTests/BooleanExtensionsTests.IsTrue.cs, tests/BB84.ExtensionsTests/ByteExtensionsTests.IsNull.cs, tests/BB84.ExtensionsTests/FloatExtensionsTests.IsNull.cs, tests/BB84.ExtensionsTests/FloatExtensionsTests.cs, tests/BB84.ExtensionsTests/IntegerExtensionsTests.IsNull.cs
changes:
- added `IsNull` for boolean
- added `IsNull` for byte array
- added `IsNull` for float
- added `IsNull` for integer
- bumped version to `1.8.1`
closes #67
=> feat: add some null checks

src/BB84.Extensions/DoubleExtensions.IsNull.cs, src/BB84.Extensions/DoubleExtensions.cs, tests/BB84.ExtensionsTests/DoubleExtensionsTests.IsNull.cs, tests/BB84.ExtensionsTests/DoubleExtensionsTests.cs
changes:
- added `IsNull` method
closes #70
=> feat: double extensions is null method

src/BB84.Extensions/DecimalExtensions.IsNull.cs, src/BB84.Extensions/DecimalExtensions.cs, tests/BB84.ExtensionsTests/DecimalExtensionsTests.IsNull.cs, tests/BB84.ExtensionsTests/DecimalExtensionsTests.cs
changes:
- added IsNull method
closes #69
=> feat: decimal extensions is null method

src/BB84.Extensions/ListExtensions.AddIfNotNull.cs, src/BB84.Extensions/ListExtensions.AddRangeIfNotNull.cs, src/BB84.Extensions/ObjectExtensions.cs, tests/BB84.ExtensionsTests/EnumerableExtensionsTests.ForEach.cs
changes:
- added the `ThrowIfNull` method
- some other small fixes
closes #73
=> fix: use ArgumentNullException throw helper

CODE_OF_CONDUCT.md
changes:
- added `CODE_OF_CONDUCT.md`
closes #75
=> chore: code of conduct

src/BB84.Extensions/ColorExtensions.ToARGBHexString.cs, src/BB84.Extensions/ColorExtensions.ToRGBHexString.cs, src/BB84.Extensions/ColorExtensions.cs, tests/BB84.ExtensionsTests/ColorExtensionsTests.ToARGBHexString.cs, tests/BB84.ExtensionsTests/ColorExtensionsTests.ToRGBHexString.cs, tests/BB84.ExtensionsTests/ColorExtensionsTests.cs
changes:
- added the `ToARGBHexString` method
- added the `ToRGBHexString` method
closes #77
=> feat: color extension to convert to hex string

Directory.Build.props, tests/BB84.ExtensionsTests/DateTimeExtensionTests.EndOfMonth.cs, tests/BB84.ExtensionsTests/DateTimeExtensionTests.EndOfWeek.cs, tests/BB84.ExtensionsTests/DateTimeExtensionTests.StartOfMonth.cs, tests/BB84.ExtensionsTests/DateTimeExtensionTests.StartOfWeek.cs, tests/BB84.ExtensionsTests/DateTimeExtensionTests.cs
changes:
- version bumped to `2.0.0`
- unit test fixes applied
closes #79
=> chore: version bump to 2.0.0

BB84.Extensions.sln, Directory.Build.targets, Directory.Packages.props, src/BB84.Extensions/BB84.Extensions.csproj, tests/BB84.ExtensionsTests/BB84.ExtensionsTests.csproj
changes:
- added `Directory.Packages.props`
- modified project files
closes #91
=> feat: add directory packages props file

Directory.Build.props, Directory.Packages.props, README.md, src/BB84.Extensions/ColorExtensions.FromARGBHexString.cs, src/BB84.Extensions/ColorExtensions.FromRGBHexString.cs, src/BB84.Extensions/ColorExtensions.ToARGBHexString.cs, src/BB84.Extensions/ColorExtensions.ToRGBHexString.cs, tests/BB84.ExtensionsTests/ColorExtensionsTests.FromARGBHexString.cs, tests/BB84.ExtensionsTests/ColorExtensionsTests.FromRGBHexString.cs
changes:
- [nuget packages updated](https://github.com/BoBoBaSs84/BB84.Extensions/commit/9e7963c18211a353aa2a0570b16f72086c0531aa)
- [descriptions fixed](https://github.com/BoBoBaSs84/BB84.Extensions/commit/8feed01c82a3ef8c28ed5e3dd8133a8602dafe10)
- [new methods added](https://github.com/BoBoBaSs84/BB84.Extensions/commit/9fe2f9e1bd739935230580adf22a2fe1f329f748)
- [unit tests added](https://github.com/BoBoBaSs84/BB84.Extensions/commit/892bfd1bfa2a799a7a9a84a521e9325fb7c86185)
- [readme fixed](https://github.com/BoBoBaSs84/BB84.Extensions/commit/acd18c3f54da8de9ab761eceb206021d2b7e20a8)
closes #103
=> feat: more color extension methods

src/BB84.Extensions/ColorExtensions.FromArgbByteArray.cs, src/BB84.Extensions/ColorExtensions.FromRgbByteArray.cs, src/BB84.Extensions/ColorExtensions.ToArgbByteArray.cs, src/BB84.Extensions/ColorExtensions.ToRgbByteArray.cs, tests/BB84.ExtensionsTests/ColorExtensionsTests.FromARGBHexString.cs, tests/BB84.ExtensionsTests/ColorExtensionsTests.FromArgbByteArray.cs, tests/BB84.ExtensionsTests/ColorExtensionsTests.FromRGBHexString.cs, tests/BB84.ExtensionsTests/ColorExtensionsTests.FromRgbByteArray.cs, tests/BB84.ExtensionsTests/ColorExtensionsTests.ToARGBHexString.cs, tests/BB84.ExtensionsTests/ColorExtensionsTests.ToArgbByteArray.cs, tests/BB84.ExtensionsTests/ColorExtensionsTests.ToRGBHexString.cs, tests/BB84.ExtensionsTests/ColorExtensionsTests.ToRgbByteArray.cs, tests/BB84.ExtensionsTests/ColorExtensionsTests.cs
changes:
- [feat: more color extension methods](https://github.com/BoBoBaSs84/BB84.Extensions/commit/10146163b2ddeae47e8e1a1893681d472d9e03dd)
- [feat: four extension methods added](https://github.com/BoBoBaSs84/BB84.Extensions/commit/f60ed86561860d90f38eb39bda757f8be1de0ac1)
- [tests: unit tests added and fixed](https://github.com/BoBoBaSs84/BB84.Extensions/commit/d19a3202c72c3607af75bf81b5cac2ef9bae9927)
closes #105
=> feat: colors to and from byte array

src/BB84.Extensions/DateTimeExtensions.EndOfFiscalYear.cs, src/BB84.Extensions/DateTimeExtensions.EndOfYear.cs, src/BB84.Extensions/DateTimeExtensions.StartOfFiscalYear.cs, src/BB84.Extensions/DateTimeExtensions.StartOfYear.cs, tests/BB84.ExtensionsTests/DateTimeExtensionTests.EndOfFiscalYear.cs, tests/BB84.ExtensionsTests/DateTimeExtensionTests.EndOfYear.cs, tests/BB84.ExtensionsTests/DateTimeExtensionTests.StartOfFiscalYear.cs, tests/BB84.ExtensionsTests/DateTimeExtensionTests.StartOfYear.cs, tests/BB84.ExtensionsTests/DateTimeExtensionTests.cs
changes:
- [feat: four new extension methods added](https://github.com/BoBoBaSs84/BB84.Extensions/commit/bc5198e20c26adf540c664845ca9e74b9c6e1b87)
- [tests: unit tests added](https://github.com/BoBoBaSs84/BB84.Extensions/commit/a1f58aaaf16389a0b684d66b81447891feb8e3e4)
closes #107
=> feat: start of year and start of fiscal year methods

src/BB84.Extensions/DateTimeExtensions.WeekOfYear.cs, tests/BB84.ExtensionsTests/DateTimeExtensionTests.WeekOfYear.cs, tests/BB84.ExtensionsTests/DateTimeExtensionTests.cs
changes:
- week of the year method added
closes #110
=> feat: week of the year method

tests/BB84.ExtensionsTests/DateTimeExtensionTests.WeekOfYear.cs, tests/BB84.ExtensionsTests/DateTimeExtensionTests.cs
changes:
- unit tests fixed
closes #117
=> fix: get week of year unit tests

src/BB84.Extensions/BooleanExtensions.IsFalse.cs, src/BB84.Extensions/BooleanExtensions.IsTrue.cs, tests/BB84.ExtensionsTests/BooleanExtensionsTests.IsFalse.cs, tests/BB84.ExtensionsTests/BooleanExtensionsTests.IsTrue.cs
changes:
- [feat: nullable bool methods added](https://github.com/BoBoBaSs84/BB84.Extensions/commit/30f88abff130b2a1e39b9dafae421e2c79fc1a11)
- [feat: unit tests for nullable bool methods added](https://github.com/BoBoBaSs84/BB84.Extensions/commit/1110f29701002ed2a459064e1878f78f23898017)
closes #124
=> feat: more boolean extensions methods

src/BB84.Extensions/StreamExtensions.cs, src/BB84.Extensions/TaskExtensions.cs, tests/BB84.ExtensionsTests/TaskExtensionsTests.ToSafeSync.cs, tests/BB84.ExtensionsTests/TaskExtensionsTests.ToSafeVoid.cs, tests/BB84.ExtensionsTests/TaskExtensionsTests.ToSafeVoidAsync.cs, tests/BB84.ExtensionsTests/TaskExtensionsTests.cs
changes:
- [fix: comments fixed](https://github.com/BoBoBaSs84/BB84.Extensions/commit/e08be95d5d3e8231fdbc1cc51d51998579670e90)
- [feat: task extension methods added](https://github.com/BoBoBaSs84/BB84.Extensions/commit/f3650fdf2da0d85fb92b5791feb7a7b96db32969)
- [feat: task extension unit tests added](https://github.com/BoBoBaSs84/BB84.Extensions/commit/6c594924e493042866d6807ec7da2ed0d9e36b20)
closes #125
=> feat: task extension methods

BB84.Extensions.sln, Directory.Build.targets, Directory.Packages.props, src/BB84.Extensions/BB84.Extensions.csproj, src/BB84.Extensions/HttpClientExtensions.cs, tests/BB84.ExtensionsTests/HttpClientExtensionsTests.cs
changes:
- [feat: added System.Net.Http package](https://github.com/BoBoBaSs84/BB84.Extensions/commit/1e056cdfbe40d8e36d8f0dade28dd36d1954ea44)
- [feat: removed tragets file](https://github.com/BoBoBaSs84/BB84.Extensions/commit/4029b9c69c856a225d7d38711ddc77c6b873d801)
- [feat: added extension methods](https://github.com/BoBoBaSs84/BB84.Extensions/commit/41b4177f47eeecea4db5708d349d09043a9e1cfc)
- [added: extension methods unit tests](https://github.com/BoBoBaSs84/BB84.Extensions/commit/69e9f9403a51be3c9981ed24de0df50727587e7f)
closes #128
=> feat: http client extensions

README.md, src/BB84.Extensions/EnumeratorExtensions.GetValues.cs
changes:
- [fix: method get values fixed](https://github.com/BoBoBaSs84/BB84.Extensions/commit/8438c5e2913c4b795e22a9749e93c73c4d13e115)
- [chore: read me improved](https://github.com/BoBoBaSs84/BB84.Extensions/commit/49d90c014a027ca18e8631bc22c9bdeb77fa4445)
closes #134
=> fix: do not use cast use oftype

src/BB84.Extensions/HttpClientExtensions.cs, src/BB84.Extensions/StringExtensions.RemoveLinebreak.cs, src/BB84.Extensions/StringExtensions.RemoveWhitespace.cs, tests/BB84.ExtensionsTests/HttpClientExtensionsTests.cs
changes:
- [docs: fixed some comments in the http client extension methods](https://github.com/BoBoBaSs84/BB84.Extensions/commit/8fd7e16d5016b2bc5948c229f8a30f94ed9a683e)
- [refactor: renamed http client extension methods](https://github.com/BoBoBaSs84/BB84.Extensions/commit/963b2027f1608835060927fc57c4f85cb6668814)
- [feat: new http client timeout extension method and unit tests added](https://github.com/BoBoBaSs84/BB84.Extensions/commit/d872b7efc259ee3d07b5796a9c164a977d50e157)
- [docs: fixed some comments in the string extension methods](https://github.com/BoBoBaSs84/BB84.Extensions/commit/0614bd5b3e1fe936bee1a040bd27761d2b5a7274)
closes #136
=> docs: fix some issues with the documentation

Directory.Packages.props
=> chore(deps): updated System.Text.Json from 8.0.4 to 8.0.5

.github/workflows/ci.yml, src/BB84.Extensions/DateTimeExtensions.WeekOfYear.cs, src/BB84.Extensions/Serialization/JsonExtensions.cs, tests/BB84.ExtensionsTests/DateTimeExtensionTests.WeekOfYear.cs, tests/BB84.ExtensionsTests/DateTimeExtensionTests.cs
=> feat: change pipeline runner

src/BB84.WinForms.Extensions/PictureBoxExtensions.cs, tests/BB84.WinForms.Extensions.Tests/PictureBoxExtensionsTests.cs
changes:
- extension methods added
closes #167
=> feat: `PictureBox` control extensions added

src/BB84.Extensions/HttpClientExtensions.cs, tests/BB84.Extensions.Tests/HttpClientExtensionsTests.cs
changes:
- basic authentication extension method added
closes #169
=> feat: http client extension methods added

src/BB84.WinForms.Extensions/DateTimePickerExtensions.cs, tests/BB84.WinForms.Extensions.Tests/DateTimePickerExtensionsTests.cs
changes:
- date time picker extension methods added
closes #171
=> feat: date time picker min and max date binding added

Directory.Packages.props
changes:
- `MSTest` updated to `3.8.3`
- `System.Text.Json` updated to `9.0.5`
=> chore(deps): nuget packages updated

src/BB84.WinForms.Extensions/LabelExtensions.cs, tests/BB84.WinForms.Extensions.Tests/LabelExtensionsTests.cs
changes:
- [feat: label extension methods added](https://github.com/BoBoBaSs84/BB84.Extensions/commit/6527ad26571616343a48518ccd9c2fe293e6e7a5)
- [feat: label extension unit tests added](https://github.com/BoBoBaSs84/BB84.Extensions/commit/890d92691e0bbf49c3c169b6fdf7ddd629954829)
closes #177
=> feat: label control extension methods

src/BB84.WinForms.Extensions/ButtonExtensions.cs, src/BB84.WinForms.Extensions/CheckBoxExtensions.cs, src/BB84.WinForms.Extensions/ComboBoxExtensions.cs, src/BB84.WinForms.Extensions/DataGridExtensions.cs, src/BB84.WinForms.Extensions/DataGridViewExtensions.cs, src/BB84.WinForms.Extensions/DateTimePickerExtensions.cs, src/BB84.WinForms.Extensions/ListBoxExtensions.cs, src/BB84.WinForms.Extensions/ListViewExtensions.cs, src/BB84.WinForms.Extensions/MaskedTextBoxExtensions.cs, src/BB84.WinForms.Extensions/MonthCalendarExtensions.cs, src/BB84.WinForms.Extensions/NumericUpDownExtensions.cs, src/BB84.WinForms.Extensions/PictureBoxExtensions.cs, src/BB84.WinForms.Extensions/ProgressBarExtensions.cs, src/BB84.WinForms.Extensions/PropertyGridExtensions.cs, src/BB84.WinForms.Extensions/RadioButtonExtensions.cs, src/BB84.WinForms.Extensions/RichTextBoxExtensions.cs, src/BB84.WinForms.Extensions/TextBoxExtensions.cs, src/BB84.WinForms.Extensions/TrackBarExtensions.cs, src/BB84.WinForms.Extensions/TreeViewExtensions.cs, tests/BB84.WinForms.Extensions.Tests/ButtonExtensionsTests.cs
changes:
- [feat: overall comments improved](https://github.com/BoBoBaSs84/BB84.Extensions/commit/348eddad313e80723b4fb769f1a5750a3bc73019)
- [fix: missing unit test added](https://github.com/BoBoBaSs84/BB84.Extensions/commit/9272d5a4b61a0525ca58e757f6614fbb4b3582a6)
closes #179
=> feat: refactor the win form extensions comments

src/BB84.Extensions/Common/Constants.cs, src/BB84.Extensions/HttpClientExtensions.cs, src/BB84.Extensions/HttpRequestMessageExtensions.cs, tests/BB84.Extensions.Tests/HttpRequestMessageExtensionsTests.cs
changes:
- two new extension methods added
closes #183
=> feat: added http request message extension methods

src/BB84.Extensions/TaskExtensions.cs, tests/BB84.Extensions.Tests/TaskExtensionsTests.AsSync.cs
changes:
- [feat: as sync method and unit test added](https://github.com/BoBoBaSs84/BB84.Extensions/commit/cfa60b275eda752a78d01748ac18a33c4e3fb9e6)
closes #187
=> feat: as sync method and unit test added

src/BB84.WinForms.Extensions/GroupBoxExtensions.cs, src/BB84.WinForms.Extensions/LabelExtensions.cs, tests/BB84.WinForms.Extensions.Tests/GroupBoxExtensionsTests.cs
**Changes:**
- [feat: groupbox extension methods added](https://github.com/BoBoBaSs84/BB84.Extensions/commit/126be1bc8c39ebbe4d2473909084d90d0c8fbb0c)
- [fix: missing license header added](https://github.com/BoBoBaSs84/BB84.Extensions/commit/3e1c229a19ef01893ee16916f8c59ae3148454bb)
closes #202
=> feat: add groupbox extensions

src/BB84.Extensions/LongExtensions.cs, tests/BB84.Extensions.Tests/LongExtensionsTests.cs
feat: long extension methods added
changes:
- added null check methods
- added default check methods
- added for loop method
closes #219
=> feat: long extension methods added
